package curso.java.ejercicios.ficheros.interfaces;

public interface IFicheros {
	int EJERCICIO1_POSICION_NOMBRE = 0;
	int EJERCICIO1_POSICION_APELLIDOS = 1;
	int EJERCICIO1_POSICION_DNI = 2;
	int EJERCICIO1_POSICION_ASIGNATURAS = 3;
	
	
	int EJERCICIO2_POSICION_COLEGIO = 0;
	int EJERCICIO2_POSICION_NOMBRE = 1;
	int EJERCICIO2_POSICION_APELLIDOS = 2;
	int EJERCICIO2_POSICION_DNI = 3;
	int EJERCICIO2_POSICION_ASIGNATURAS = 4;
}
